import venueArena from "@/assets/tournament/venue-arena.jpg";
import venueNova from "@/assets/tournament/venue-nova.jpg";
import venuePixel from "@/assets/tournament/venue-pixel.jpg";
import {
  gamingCenterDetailSchema,
  type GamingCenterDetailData,
  type GamingCenterDetailRepository,
} from "./gaming-center-detail-contract";

const centers: GamingCenterDetailData[] = [
  gamingCenterDetailSchema.parse({
    schemaVersion: 1,
    centerId: "c1",
    publicId: "c1",
    publicationState: "published",
    name: "Arena Gaming Center",
    verified: true,
    city: { cityId: "karaj", slug: "karaj", name: "کرج" },
    district: "عظیمیه",
    summary: "مرکز گیمینگ در عظیمیه کرج با فضای رقابتی و تجهیزات مناسب برای برگزاری مسابقات حضوری.",
    description: "Arena Gaming Center برای بازیکنانی طراحی شده که می‌خواهند در فضای حضوری بازی کنند، امکانات مرکز را پیش از مراجعه ببینند و مسابقات برنامه‌ریزی‌شده در این مرکز را از یک مسیر مشخص دنبال کنند.",
    equipmentLabels: ["PS5", "مانیتور ۱۴۴ هرتز", "دسته حرفه‌ای"],
    coverImage: venueArena,
    galleryImages: [],
    upcomingTournamentCount: 3,
    publicAddress: {
      streetAddress: "عظیمیه، بلوار شریعتی",
      addressLocality: "کرج",
      addressRegion: "البرز",
      postalCode: null,
      addressCountry: "IR",
      displayAddress: "کرج، عظیمیه، بلوار شریعتی",
    },
    publicPhone: "+982612345678",
    openingHours: [
      { dayOfWeek: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday"], opens: "12:00", closes: "23:00" },
      { dayOfWeek: ["Thursday", "Friday"], opens: "11:00", closes: "23:30" },
    ],
    mapUrl: null,
    tournaments: [
      {
        tournamentId: "t1",
        tournamentSlug: "fc26-karaj-champions-cup",
        title: "جام قهرمانان کرج",
        game: { gameId: "eafc26", slug: "ea-fc-26", name: "EA FC 26" },
        startsAt: "2026-09-18T20:30:00+03:30",
        displayDate: "جمعه ۲۷ شهریور",
        displayTime: "۲۰:۳۰",
        registrationState: "filling",
      },
      {
        tournamentId: "t6",
        tournamentSlug: "eafc26-winter-cup-karaj",
        title: "جام آزاد EA FC 26 کرج",
        game: { gameId: "eafc26", slug: "ea-fc-26", name: "EA FC 26" },
        startsAt: "2026-09-26T19:00:00+03:30",
        displayDate: "شنبه ۴ مهر",
        displayTime: "۱۹:۰۰",
        registrationState: "upcoming",
      },
    ],
  }),
  gamingCenterDetailSchema.parse({
    schemaVersion: 1,
    centerId: "c2",
    publicId: "c2",
    publicationState: "published",
    name: "Nova Gaming",
    verified: true,
    city: { cityId: "tehran", slug: "tehran", name: "تهران" },
    district: "سعادت‌آباد",
    summary: "مرکز گیمینگ در سعادت‌آباد تهران با فضای میزبانی رقابت و امکانات کنسولی برای رویدادهای حضوری.",
    description: "Nova Gaming یک مرکز حضوری برای بازی و رقابت در غرب تهران است. در این صفحه می‌توانی اطلاعات عمومی مراجعه، امکانات منتشرشده و مسابقات پیش‌رویی را که این مرکز میزبانی می‌کند بررسی کنی.",
    equipmentLabels: ["PS5", "تلویزیون ۴K", "صندلی گیمینگ"],
    coverImage: venueNova,
    galleryImages: [],
    upcomingTournamentCount: 2,
    publicAddress: {
      streetAddress: "سعادت‌آباد، بلوار دریا",
      addressLocality: "تهران",
      addressRegion: "تهران",
      postalCode: null,
      addressCountry: "IR",
      displayAddress: "تهران، سعادت‌آباد، بلوار دریا",
    },
    publicPhone: "+982122345678",
    openingHours: [
      { dayOfWeek: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"], opens: "11:00", closes: "23:30" },
      { dayOfWeek: ["Friday"], opens: "12:00", closes: "23:30" },
    ],
    mapUrl: null,
    tournaments: [
      {
        tournamentId: "t2",
        tournamentSlug: "tekken-night-04",
        title: "Tekken Night #04",
        game: { gameId: "tekken8", slug: "tekken-8", name: "Tekken 8" },
        startsAt: "2026-09-17T18:00:00+03:30",
        displayDate: "پنج‌شنبه ۲۶ شهریور",
        displayTime: "۱۸:۰۰",
        registrationState: "open",
      },
      {
        tournamentId: "t4",
        tournamentSlug: "efootball-weekly-league",
        title: "لیگ هفتگی eFootball",
        game: { gameId: "efootball", slug: "efootball", name: "eFootball" },
        startsAt: "2026-09-20T17:30:00+03:30",
        displayDate: "یکشنبه ۲۹ شهریور",
        displayTime: "۱۷:۳۰",
        registrationState: "open",
      },
    ],
  }),
  gamingCenterDetailSchema.parse({
    schemaVersion: 1,
    centerId: "c3",
    publicId: "c3",
    publicationState: "published",
    name: "Pixel House",
    verified: true,
    city: { cityId: "tehran", slug: "tehran", name: "تهران" },
    district: "نارمک",
    summary: "مرکز گیمینگ در نارمک تهران با سیستم‌های PC و فضای اختصاصی برای مسابقات تیمی و رقابت حضوری.",
    description: "Pixel House روی بازی‌های رایانه‌ای و رقابت‌های تیمی تمرکز دارد. بازیکنان می‌توانند امکانات اعلام‌شده مرکز، محدوده مراجعه و مسابقات حضوری پیش‌رو را پیش از انتخاب رویداد بررسی کنند.",
    equipmentLabels: ["PC گیمینگ", "استیج مسابقه", "پخش زنده"],
    coverImage: venuePixel,
    galleryImages: [],
    upcomingTournamentCount: 2,
    publicAddress: {
      streetAddress: "نارمک، خیابان آیت",
      addressLocality: "تهران",
      addressRegion: "تهران",
      postalCode: null,
      addressCountry: "IR",
      displayAddress: "تهران، نارمک، خیابان آیت",
    },
    publicPhone: null,
    openingHours: [
      { dayOfWeek: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], opens: "13:00", closes: "23:30" },
    ],
    mapUrl: null,
    tournaments: [
      {
        tournamentId: "t3",
        tournamentSlug: "mortal-kombat-clash",
        title: "Mortal Kombat Clash",
        game: { gameId: "mk", slug: "mortal-kombat", name: "Mortal Kombat" },
        startsAt: "2026-09-19T19:00:00+03:30",
        displayDate: "شنبه ۲۸ شهریور",
        displayTime: "۱۹:۰۰",
        registrationState: "closed",
      },
      {
        tournamentId: "t5",
        tournamentSlug: "cs2-open-cup",
        title: "CS2 Open Cup",
        game: { gameId: "cs2", slug: "counter-strike-2", name: "Counter-Strike 2" },
        startsAt: "2026-09-25T15:00:00+03:30",
        displayDate: "جمعه ۳ مهر",
        displayTime: "۱۵:۰۰",
        registrationState: "open",
      },
    ],
  }),
  gamingCenterDetailSchema.parse({
    schemaVersion: 1,
    centerId: "c4",
    publicId: "c4",
    publicationState: "published",
    name: "Gohardasht Play",
    verified: false,
    city: { cityId: "karaj", slug: "karaj", name: "کرج" },
    district: "گوهردشت",
    summary: "مرکز گیمینگ در گوهردشت کرج برای بازیکنانی که می‌خواهند رویدادهای محلی و رقابت حضوری را دنبال کنند.",
    description: "Gohardasht Play در فهرست عمومی مراکز Turnoment حضور دارد. در این صفحه می‌توانی امکاناتی را که برای مراجعه عمومی منتشر شده و مسابقات پیش‌روی مرکز را بررسی کنی.",
    equipmentLabels: ["PS5", "PC گیمینگ"],
    coverImage: null,
    galleryImages: [],
    upcomingTournamentCount: null,
    publicAddress: null,
    publicPhone: null,
    openingHours: [],
    mapUrl: null,
    tournaments: [
      {
        tournamentId: "t7",
        tournamentSlug: "tekken-rookie-night",
        title: "Tekken Rookie Night",
        game: { gameId: "tekken8", slug: "tekken-8", name: "Tekken 8" },
        startsAt: "2026-09-12T18:00:00+03:30",
        displayDate: "شنبه ۲۱ شهریور",
        displayTime: "۱۸:۰۰",
        registrationState: "open",
      },
    ],
  }),
];

export function getGamingCenterDetailFixture(publicId: string): GamingCenterDetailData | null {
  return centers.find((center) => center.publicId === publicId) ?? null;
}

export class MockGamingCenterDetailRepository implements GamingCenterDetailRepository {
  async getByPublicId(publicId: string): Promise<GamingCenterDetailData | null> {
    return getGamingCenterDetailFixture(publicId);
  }
}
