/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostRouteImport } from './routes/host'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CentersIndexRouteImport } from './routes/centers.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as ServicesRequestRouteImport } from './routes/services.request'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PlayersUsernameRouteImport } from './routes/players.$username'
import { Route as PaymentResultRouteImport } from './routes/payment.result'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard.wishlist'
import { Route as DashboardTournamentsRouteImport } from './routes/dashboard.tournaments'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard.teams'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardRivalriesRouteImport } from './routes/dashboard.rivalries'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMatchesRouteImport } from './routes/dashboard.matches'
import { Route as DashboardChallengesRouteImport } from './routes/dashboard.challenges'
import { Route as DashboardAddressesRouteImport } from './routes/dashboard.addresses'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as CentersIdRouteImport } from './routes/centers.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as TournamentsIdRegisterRouteImport } from './routes/tournaments.$id_.register'
import { Route as MatchesIdResultRouteImport } from './routes/matches.$id_.result'
import { Route as MatchesIdDisputeRouteImport } from './routes/matches.$id_.dispute'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CentersIndexRoute = CentersIndexRouteImport.update({
  id: '/centers/',
  path: '/centers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRequestRoute = ServicesRequestRouteImport.update({
  id: '/services/request',
  path: '/services/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersUsernameRoute = PlayersUsernameRouteImport.update({
  id: '/players/$username',
  path: '/players/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment/result',
  path: '/payment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTournamentsRoute = DashboardTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRivalriesRoute = DashboardRivalriesRouteImport.update({
  id: '/rivalries',
  path: '/rivalries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMatchesRoute = DashboardMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChallengesRoute = DashboardChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddressesRoute = DashboardAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const CentersIdRoute = CentersIdRouteImport.update({
  id: '/centers/$id',
  path: '/centers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRegisterRoute = TournamentsIdRegisterRouteImport.update({
  id: '/tournaments/$id_/register',
  path: '/tournaments/$id/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdResultRoute = MatchesIdResultRouteImport.update({
  id: '/matches/$id_/result',
  path: '/matches/$id/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdDisputeRoute = MatchesIdDisputeRouteImport.update({
  id: '/matches/$id_/dispute',
  path: '/matches/$id/dispute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/centers/$id': typeof CentersIdRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rivalries': typeof DashboardRivalriesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/games/$slug': typeof GamesSlugRoute
  '/payment/result': typeof PaymentResultRoute
  '/players/$username': typeof PlayersUsernameRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/request': typeof ServicesRequestRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/centers/': typeof CentersIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/matches/$id/dispute': typeof MatchesIdDisputeRoute
  '/matches/$id/result': typeof MatchesIdResultRoute
  '/tournaments/$id/register': typeof TournamentsIdRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/centers/$id': typeof CentersIdRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rivalries': typeof DashboardRivalriesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/games/$slug': typeof GamesSlugRoute
  '/payment/result': typeof PaymentResultRoute
  '/players/$username': typeof PlayersUsernameRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/request': typeof ServicesRequestRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/blog': typeof BlogIndexRoute
  '/centers': typeof CentersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/games': typeof GamesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/matches/$id/dispute': typeof MatchesIdDisputeRoute
  '/matches/$id/result': typeof MatchesIdResultRoute
  '/tournaments/$id/register': typeof TournamentsIdRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/centers/$id': typeof CentersIdRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/matches': typeof DashboardMatchesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/rivalries': typeof DashboardRivalriesRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/tournaments': typeof DashboardTournamentsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/games/$slug': typeof GamesSlugRoute
  '/payment/result': typeof PaymentResultRoute
  '/players/$username': typeof PlayersUsernameRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/services/request': typeof ServicesRequestRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/blog/': typeof BlogIndexRoute
  '/centers/': typeof CentersIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/games/': typeof GamesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/matches/$id_/dispute': typeof MatchesIdDisputeRoute
  '/matches/$id_/result': typeof MatchesIdResultRoute
  '/tournaments/$id_/register': typeof TournamentsIdRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/host'
    | '/login'
    | '/ranking'
    | '/register'
    | '/rules'
    | '/blog/$slug'
    | '/category/$slug'
    | '/centers/$id'
    | '/dashboard/achievements'
    | '/dashboard/addresses'
    | '/dashboard/challenges'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/rivalries'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/dashboard/tournaments'
    | '/dashboard/wishlist'
    | '/games/$slug'
    | '/payment/result'
    | '/players/$username'
    | '/products/$slug'
    | '/services/request'
    | '/tournaments/$id'
    | '/blog/'
    | '/centers/'
    | '/dashboard/'
    | '/games/'
    | '/products/'
    | '/services/'
    | '/tournaments/'
    | '/matches/$id/dispute'
    | '/matches/$id/result'
    | '/tournaments/$id/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/host'
    | '/login'
    | '/ranking'
    | '/register'
    | '/rules'
    | '/blog/$slug'
    | '/category/$slug'
    | '/centers/$id'
    | '/dashboard/achievements'
    | '/dashboard/addresses'
    | '/dashboard/challenges'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/rivalries'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/dashboard/tournaments'
    | '/dashboard/wishlist'
    | '/games/$slug'
    | '/payment/result'
    | '/players/$username'
    | '/products/$slug'
    | '/services/request'
    | '/tournaments/$id'
    | '/blog'
    | '/centers'
    | '/dashboard'
    | '/games'
    | '/products'
    | '/services'
    | '/tournaments'
    | '/matches/$id/dispute'
    | '/matches/$id/result'
    | '/tournaments/$id/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/host'
    | '/login'
    | '/ranking'
    | '/register'
    | '/rules'
    | '/blog/$slug'
    | '/category/$slug'
    | '/centers/$id'
    | '/dashboard/achievements'
    | '/dashboard/addresses'
    | '/dashboard/challenges'
    | '/dashboard/matches'
    | '/dashboard/notifications'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/dashboard/rivalries'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/dashboard/tournaments'
    | '/dashboard/wishlist'
    | '/games/$slug'
    | '/payment/result'
    | '/players/$username'
    | '/products/$slug'
    | '/services/request'
    | '/tournaments/$id'
    | '/blog/'
    | '/centers/'
    | '/dashboard/'
    | '/games/'
    | '/products/'
    | '/services/'
    | '/tournaments/'
    | '/matches/$id_/dispute'
    | '/matches/$id_/result'
    | '/tournaments/$id_/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  HostRoute: typeof HostRoute
  LoginRoute: typeof LoginRoute
  RankingRoute: typeof RankingRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CentersIdRoute: typeof CentersIdRoute
  GamesSlugRoute: typeof GamesSlugRoute
  PaymentResultRoute: typeof PaymentResultRoute
  PlayersUsernameRoute: typeof PlayersUsernameRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ServicesRequestRoute: typeof ServicesRequestRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CentersIndexRoute: typeof CentersIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  MatchesIdDisputeRoute: typeof MatchesIdDisputeRoute
  MatchesIdResultRoute: typeof MatchesIdResultRoute
  TournamentsIdRegisterRoute: typeof TournamentsIdRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/centers/': {
      id: '/centers/'
      path: '/centers'
      fullPath: '/centers/'
      preLoaderRoute: typeof CentersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/request': {
      id: '/services/request'
      path: '/services/request'
      fullPath: '/services/request'
      preLoaderRoute: typeof ServicesRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$username': {
      id: '/players/$username'
      path: '/players/$username'
      fullPath: '/players/$username'
      preLoaderRoute: typeof PlayersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/result': {
      id: '/payment/result'
      path: '/payment/result'
      fullPath: '/payment/result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tournaments': {
      id: '/dashboard/tournaments'
      path: '/tournaments'
      fullPath: '/dashboard/tournaments'
      preLoaderRoute: typeof DashboardTournamentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rivalries': {
      id: '/dashboard/rivalries'
      path: '/rivalries'
      fullPath: '/dashboard/rivalries'
      preLoaderRoute: typeof DashboardRivalriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/matches': {
      id: '/dashboard/matches'
      path: '/matches'
      fullPath: '/dashboard/matches'
      preLoaderRoute: typeof DashboardMatchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/challenges': {
      id: '/dashboard/challenges'
      path: '/challenges'
      fullPath: '/dashboard/challenges'
      preLoaderRoute: typeof DashboardChallengesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/addresses': {
      id: '/dashboard/addresses'
      path: '/addresses'
      fullPath: '/dashboard/addresses'
      preLoaderRoute: typeof DashboardAddressesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/centers/$id': {
      id: '/centers/$id'
      path: '/centers/$id'
      fullPath: '/centers/$id'
      preLoaderRoute: typeof CentersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id_/register': {
      id: '/tournaments/$id_/register'
      path: '/tournaments/$id/register'
      fullPath: '/tournaments/$id/register'
      preLoaderRoute: typeof TournamentsIdRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id_/result': {
      id: '/matches/$id_/result'
      path: '/matches/$id/result'
      fullPath: '/matches/$id/result'
      preLoaderRoute: typeof MatchesIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id_/dispute': {
      id: '/matches/$id_/dispute'
      path: '/matches/$id/dispute'
      fullPath: '/matches/$id/dispute'
      preLoaderRoute: typeof MatchesIdDisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardAddressesRoute: typeof DashboardAddressesRoute
  DashboardChallengesRoute: typeof DashboardChallengesRoute
  DashboardMatchesRoute: typeof DashboardMatchesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRivalriesRoute: typeof DashboardRivalriesRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardTournamentsRoute: typeof DashboardTournamentsRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardAddressesRoute: DashboardAddressesRoute,
  DashboardChallengesRoute: DashboardChallengesRoute,
  DashboardMatchesRoute: DashboardMatchesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRivalriesRoute: DashboardRivalriesRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardTournamentsRoute: DashboardTournamentsRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  HostRoute: HostRoute,
  LoginRoute: LoginRoute,
  RankingRoute: RankingRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  CentersIdRoute: CentersIdRoute,
  GamesSlugRoute: GamesSlugRoute,
  PaymentResultRoute: PaymentResultRoute,
  PlayersUsernameRoute: PlayersUsernameRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ServicesRequestRoute: ServicesRequestRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CentersIndexRoute: CentersIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  MatchesIdDisputeRoute: MatchesIdDisputeRoute,
  MatchesIdResultRoute: MatchesIdResultRoute,
  TournamentsIdRegisterRoute: TournamentsIdRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
